apiVersion: skaffold/v4beta8
kind: Config
deploy:
  kubectl:
    remoteManifests:
      - ./infra/k8s/*
metadata:
  name: photogallery
build:
  local:
    push: false
  artifacts:
    - image: gcr.io/photogalleryapp-408816/event-bus
      context: EventBus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: gcr.io/photogalleryapp-408816/str-mgt
      context: StorageMgmtServ
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: gcr.io/photogalleryapp-408816/usage-mnt
      context: UsageMntrServ
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: gcr.io/photogalleryapp-408816/user-acc
      context: UserAccMgmtServ
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: gcr.io/photogalleryapp-408816/view-gen
      context: view_generator_serv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
manifests:
  rawYaml:
    - Infra/k8s/event-bus-depl.yaml
    - Infra/k8s/ingress-serv.yaml
    - Infra/k8s/storage-mgmt-serv-depl.yaml
    - Infra/k8s/storage-mgmt-serv-nodeport.yaml
    - Infra/k8s/usage-mntr-serv-depl.yaml
    - Infra/k8s/usage-mntr-serv-nodeport.yaml
    - Infra/k8s/user-acc-mgmt-serv-depl.yaml
    - Infra/k8s/user-acc-mgmt-serv-nodeport.yaml
    - Infra/k8s/view-generator-serv.yaml