apiVersion: skaffold/v4beta8
kind: Config
deploy:
  kubectl:
    remoteManifests:
      - ./infra/k8s/*
metadata:
  name: photogallery
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: photogallery-409112
  artifacts:
<<<<<<< Updated upstream
    - image: gcr.io/photogalleryapp-408816/event-bus
=======
    - image: us.gcr.io/photogallery-409112/eventbus
>>>>>>> Stashed changes
      context: EventBus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
<<<<<<< Updated upstream
    - image: gcr.io/photogalleryapp-408816/str-mgt
=======
    - image: us.gcr.io/photogallery-409112/storagemgmtserv
>>>>>>> Stashed changes
      context: StorageMgmtServ
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
<<<<<<< Updated upstream
    - image: gcr.io/photogalleryapp-408816/usage-mnt
=======
    - image: us.gcr.io/photogallery-409112/usagemntrserv
>>>>>>> Stashed changes
      context: UsageMntrServ
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
<<<<<<< Updated upstream
    - image: gcr.io/photogalleryapp-408816/user-acc
=======
    - image: us.gcr.io/photogallery-409112/useraccmgmtserv
>>>>>>> Stashed changes
      context: UserAccMgmtServ
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
<<<<<<< Updated upstream
    - image: gcr.io/photogalleryapp-408816/view-gen
=======
    - image: us.gcr.io/photogallery-409112/view_generator_serv
>>>>>>> Stashed changes
      context: view_generator_serv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
manifests:
  rawYaml:
    - Infra/k8s/event-bus-depl.yaml
    - Infra/k8s/ingress-serv.yaml
    - Infra/k8s/storage-mgmt-serv-depl.yaml
    - Infra/k8s/storage-mgmt-serv-nodeport.yaml
    - Infra/k8s/usage-mntr-serv-depl.yaml
    - Infra/k8s/usage-mntr-serv-nodeport.yaml
    - Infra/k8s/user-acc-mgmt-serv-depl.yaml
    - Infra/k8s/user-acc-mgmt-serv-nodeport.yaml
    - Infra/k8s/view-generator-serv.yaml