apiVersion: v1
kind: Service
metadata: name:storage-mgmt-serv-nodeport-srv
spec:
  type: NodePort
  selector:
    app: storage-mgmt-serv
  ports:
    - name: posts
      protocol: TCP
      port: 4002
      targetPort: 4002
