apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-acc-mgmt-serv-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-acc-mgmt-serv
  template:
    metadata:
      labels:
        app: user-acc-mgmt-serv
    spec:
      containers:
        - name: user-acc-mgmt-serv
<<<<<<< Updated upstream
          image: us.gcr.io/photogalleryapp-408816/user-acc
=======
          image: us.gcr.io/photogallery-409112/useraccmgmtserv
>>>>>>> Stashed changes
---
apiVersion: v1
kind: Service
metadata: 
  name: user-acc-mgmt-serv-srv
spec:
  selector:
    app: user-acc-mgmt-serv
  ports:
    - name: user-acc-mgmt-serv
      protocol: TCP
      port: 4003
      targetPort: 4003